[project]
name = "mcp-erp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "mcp[cli]>=1.9.1",
    "fastapi>=0.110.0",
    "numpy>=1.24.0",
    "aiohttp>=3.9.0",
]
